### ISSUE TITLE
https://perf-html.io/ not working

### ISSUE THREAD

**Issue by TekBear** [firefox-devtools/Gecko-Profiler-Addon#133]
re: https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Profiling_with_the_Built-in_Profiler
the link https://perf-html.io/ does not work on firefox ESR 52.9 32bit all I get is a "purple" blank page and this console message:

      15:12:42.684 Content Security Policy: The page’s settings blocked the loading of a resource at blob:https://github.com/bc1e5f32-97e7-4fc0-adb2-8146754fe00d (“script-src https://assets-cdn.github.com”). 1 (unknown)

Why is this a separate github and not a regular entry on AMO? 

Before I  install  the  xpi  directly from  this repository which I found through Google search how do I confirm this is the official gecko profiler?

**Comment by julienw** [comment]
Thanks for your message!

In v52.6 the error message is `ReferenceError: WebAssembly is not defined`. I couldn't try with 52.9 because I got upgraded to v60.3-esr which works fine.

Our general rule is that we want to support latest ESR which is v60 at the moment, so I doubt we'll try to support v52 now.

> Why is this a separate github and not a regular entry on AMO?

This is a good question. @mstange, do you remember why we took this path? If this is because of the long review process that used to happen on AMO, it's not the case anymore atm.

> Before I install the xpi directly from this repository which I found through Google search how do I confirm this is the official gecko profiler?

You can look at the `devtools-html` organization's github page on https://github.com/devtools-html. You can also look at the last committer for the XPI, which is @mstange, and look at all other commits he did on github, to decide if he's a legitimate author.

**Comment by mstange** [comment]
> Why is this a separate github and not a regular entry on AMO?

Historical reasons... before we had a geckoProfiler WebExtensions API, we were using a blob of asm.js for symbolication, which cannot be reviewed usefully, so it wouldn't have been eligible to list on AMO.
Now that we're using a WebExtension and the geckoProfiler API, we could reconsider this. But it hasn't seemed important up to now; you're literally the first person asking about this in about two years.

> Before I install the xpi directly from this repository which I found through Google search how do I confirm this is the official gecko profiler?

You can download the xpi, unzip it, look at its manifest.json, see that the ID is `geckoprofiler@mozilla.com`, and trust that the AMO signing process wouldn't have let an unauthorized party sign the add-on with such an ID (or would at least have revoked the signature by now).

**Comment by past** [comment]
Hopefully we will be able to have the add-on be served from profiler.firefox.com or similar, soon.

**Comment by julienw** [comment]
> Hopefully we will be able to have the add-on be served from profiler.firefox.com or similar, soon.

Actually this works already :)

**Comment by gregtatum** [comment]
Closing as no longer valid with the new recording workflow.
