### ISSUE TITLE
Before gathering profiles, pause the profiler

### ISSUE THREAD

**Issue by mikeconley** [firefox-devtools/Gecko-Profiler-Addon#8]
@schien suggested this, and I think it's a good one: we normally open up the Cleopatra tab, and _then_ do the gathering of the profiles. I _think_ that's still how the new add-on works. The problem with that is that we end up seeing the activity for opening up Cleopatra in the profile.

We should probably try not to capture that Cleopatra part. Maybe we can pause the profiler before opening up Cleopatra and gathering the profiles.

**Comment by schien** [comment]
pull request provided in #9

**Comment by mstange** [comment]
The description of the problem is slightly inaccurate - the addon calls getProfileDataAsync first, and then opens the new tab. However, due to [bug 1321617](https://bugzilla.mozilla.org/show_bug.cgi?id=1321617) the parent process profile also contains the time that passed while the content process captured its own profile. I've accepted #9 so that we don't have to wait for [bug 1321617](https://bugzilla.mozilla.org/show_bug.cgi?id=1321617) to be fixed.
