### ISSUE TITLE
Should make it more clear that the profiler can't be started with a private browser window open

### ISSUE THREAD

**Issue by mikeconley** [firefox-devtools/Gecko-Profiler-Addon#96]
STR:

1. Turn the profiler add-on off.
2. Open up a private browsing window
3. Switch back to the original normal browsing window
4. Attempt to start the profiler.

ER:

At least for some folks, they might expect the profiler to start.

AR:

The profiler doesn't start. Clicking "Start" in the profiler action panel does nothing.

I understand why we're not starting the profiler - we don't want to collect potentially sensitive data from a PB window. We should, however, probably make it clear that this is why enabling the profiler isn't possible.

**Comment by Rob--W** [comment]
Another confusing UI thing: When the button of the Gecko profiler is clicked in a private browsing window, then the top bar is green and says "The profiler is recording [Discard & Stop]".

The JS console shows "TypeError: background is null" in popup.js, line 287:
https://github.com/devtools-html/Gecko-Profiler-Addon/blob/ef046a4ce85bc1375ec656502eccc1fb61bf996f/popup.js#L287

When the button is clicked in a non-private browsing window, the JS console shows "[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIProfiler.StartProfiler]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: chrome://browser/content/ext-geckoProfiler.js :: start :: line 246"  data: no]"
Indeed, this is because profiling is disabled with private browsing mode enabled: https://searchfox.org/mozilla-central/rev/c217fbde244344fedfd07b57a740c694a456dbca/tools/profiler/gecko/nsProfiler.cpp#95-100

**Comment by gregtatum** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1625541
